### ISSUE TITLE
Errors: Access level to Statamic\Eloquent\Fields\BlueprintRepository must be protected

### ISSUE THREAD

**Issue by nbeerten** [statamic/eloquent-driver#93] opened 2022-11-19 11:33 UTC
I am getting errors at both `php please eloquent:import-entries` and just visting any page accessing data from an entry. I have been able to fix this myself by editing `Statamic\Eloquent\Fields\BlueprintRepository` and changing occurrences `private` in front of properties and methods to `protected`.
This is the first error I got: 
```log
Access level to Statamic\Eloquent\Fields\BlueprintRepository::BLINK_FOUND must be protected (as in class Statamic\Fields\BlueprintRepository) or weaker
```
Screenshot of error in console:
![image](https://user-images.githubusercontent.com/59444993/202848638-e7e2f0d6-c7ec-4c3c-b2c8-9a853c22e27d.png)

**Comment by ryanmitchell** [comment] 2022-11-19 13:23
Related to:Fatal error exception after upgrade of statamic/cms to version v3.3.57 · Issue #92 · statamic/eloquent-drivergithub.comIf you have the code changes required please open a PROn 19 Nov 2022, at 11:33, nbeerten ***@***.***> wrote:﻿
I am getting errors at both php please eloquent:import-entries and just visting any page accessing data from an entry. I have been able to fix this myself by editing Statamic\Eloquent\Fields\BlueprintRepository and changing occurrences private in front of properties and methods to protected.
This is the first error I got:
Access level to Statamic\Eloquent\Fields\BlueprintRepository::BLINK_FOUND must be protected (as in class Statamic\Fields\BlueprintRepository) or weaker

Screenshot of error in console:

**Comment by nbeerten** [comment] 2022-11-19 13:32
I'd rather not open a PR myself, both because I am not sure how to do it and because I am not sure if this is caused by a wrong setup on my side, or if the change could affect other parts of the code...

**Comment by ryanmitchell** [comment] 2022-11-19 13:35
Its been caused by:

https://github.com/statamic/cms/pull/6588

If you dont get to it I'll work on the fixes required next week.

**Comment by nbeerten** [comment] 2022-11-19 13:37
Alright, so the errors are caused by a fresh update I installed literally today... Was sort of expecting that already. Thanks in advance

**Comment by jasonvarga** [comment] 2022-11-21 16:18
Duplicate of #92

**Closed by jasonvarga** 2022-11-21 16:18 UTC
