### ISSUE TITLE
Cannot create form submissions

### ISSUE THREAD

**Issue by hotmeteor** [statamic/eloquent-driver#121] opened 2023-02-03 17:08 UTC
PHP 8.1
Laravel 9.50
Statamic 3.4

***

I have a simple form:

- name
- email
- comment
- honeypot named `username`
- hidden field for the current entry called `log_id`

When I submit the form I receive a query error:

```
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "1675443750.7679" 
```
![Screen Shot 2023-02-03 at 11 07 32@2x](https://user-images.githubusercontent.com/378585/216664130-62250530-76f1-4c35-8945-e8f6430e3d5e.jpg)

Any ideas what might be causing this?

**Comment by hotmeteor** [comment] 2023-02-03 17:11
**Update:** Looks like it's this LOC in `\Statamic\Forms\Submission`, line 53:

![Screen Shot 2023-02-03 at 11 09 56@2x](https://user-images.githubusercontent.com/378585/216664641-b8a7a00a-cad2-4035-b9e8-4a2c51dcc8c9.jpg)

**Comment by jasonvarga** [comment] 2023-06-06 18:33
Closing as I can't reproduce it. See comment in #122 for more details.

**Closed by jasonvarga** 2023-06-06 18:33 UTC
