### ISSUE TITLE
Moving assets from one folder to another does not work

### ISSUE THREAD

**Issue by espenlg** [statamic/eloquent-driver#80] opened 2022-10-20 20:28 UTC
When I try to move an asset from one folder to another I get an error. Console logs identifies the problem and it looks like it searches for an actual metafile for the assets.

![196404007-897ddbce-bfb6-41df-8d14-17a69b0b4e25](https://user-images.githubusercontent.com/1135679/197051124-2606a3cf-35cb-4d94-b0a7-e8922f6ff0a5.png)

**Support details:**
Statamic 3.3.43 Pro
Laravel 8.83.23
PHP 8.0.23
r8edge/imagemap dev-main
r8edge/welcome-widget dev-main
statamic/eloquent-driver 1.0.1

**Comment by ryanmitchell** [comment] 2022-10-21 10:06
Duplicate of: https://github.com/statamic/eloquent-driver/issues/70
Should be fixed by: https://github.com/statamic/eloquent-driver/pull/71

**Comment by espenlg** [comment] 2022-10-21 10:25
> 

I did try to patch in PR #71 without any luck, but maybe it was a bit early 🤔

**Comment by ryanmitchell** [comment] 2022-10-21 10:35
Yeah I can see that now... try [this](https://github.com/statamic/eloquent-driver/pull/71/commits/9b25d9bf98a69cb755c82986e654bab429b7afba)

**Comment by leganz** [comment] 2022-10-25 13:49
@ryanmitchell  i tested the code you provided. 
1) it throws an exception (i mentioned it in the code)
2) i switched it to metaoldPath and the problem still exsits. I can still reproduce it.

**Comment by ryanmitchell** [comment] 2022-10-25 14:05
@leganz I've updated the variable. Can't see any reason for it not to be working at this point, but if you want to give me a full error trace and/or access to a sample repository I can certainly look into it further.

**Comment by leganz** [comment] 2022-10-25 14:08
I debugged the problem here... its kind of weirrd cause if you move/rename the asset => the writeMeta method will be called 3 times. The first time it has the meta information but the second and last time its gone

**Comment by leganz** [comment] 2022-10-25 15:19
I suggested a change in #71 => that will probably resolve the issue

**Comment by ryanmitchell** [comment] 2023-07-26 07:21
Fixed by https://github.com/statamic/eloquent-driver/pull/71

**Closed as completed by ryanmitchell** 2023-07-26 07:21 UTC
