### ISSUE TITLE
Required Date Field Issue

### ISSUE THREAD

**Issue by crackAT** [statamic/eloquent-driver#2] opened 2020-11-20 11:36 UTC
Hi, 

i don't know if it is an eloquent driver issue but this issue occurred since i installed this driver. 

I have a date field in a collection:
        handle: date
        field:
          type: date
          validate:
            - required

- Creating an entry, no problem. 
- Editing an entry -> 
![image](https://user-images.githubusercontent.com/6299060/99795507-30aafe00-2b2c-11eb-88d5-bc0ad2b587e3.png)
but this field has a value.
After setting a value and editing this entry again the date error occurred again.

KR M

**Comment by crackAT** [comment] 2020-11-20 13:01
Hi: The Datefield is also empty in the Database and in the Collection Overview. 
![image](https://user-images.githubusercontent.com/6299060/99802555-327abe80-2b38-11eb-9cb1-1fcda896b37e.png)

**Comment by lutory** [comment] 2020-12-15 07:00
Yes, I have the same issue. You can't save the "date" field that is part of the main fields (not the json field).

**Comment by jesseleite** [comment] 2021-09-29 21:40
@crackAT @lutory I can't reproduce this in the latest version cms and eloquent-driver. Are you still experiencing this problem?

**Comment by crackAT** [comment] 2021-09-30 07:35
Hei @jesseleite  nope it's working atm.

**Comment by jesseleite** [comment] 2021-09-30 19:07
@crackAT Awesome. I'm going to close this, but feel free to re-open an issue if needed 👍

**Closed by jesseleite** 2021-09-30 19:07 UTC
Labels: bug, can't recreate
